In [5]:
import numpy as np

In [6]:
arr=np.array([1,3,4,5],dtype=np.int64)
print("1D array:")
print(arr)

1D array:
[1 3 4 5]


In [7]:
arr2=np.array([[1,2,3],[5,6,7]],dtype=np.int64)
print("2D array:")
print(arr2)
new2_arr=arr2.reshape(6)
print("Reshaped array")
print(new2_arr)

2D array:
[[1 2 3]
 [5 6 7]]
Reshaped array
[1 2 3 5 6 7]


In [8]:
arr3=np.array([[[1,2],[2,3]],[[5,6],[8,9]]],dtype=np.int64)
print("3D array:")
print(arr3)
new3_arr=arr3.reshape(4,2)
print("Reshaped array:")
print(new3_arr)


3D array:
[[[1 2]
  [2 3]]

 [[5 6]
  [8 9]]]
Reshaped array:
[[1 2]
 [2 3]
 [5 6]
 [8 9]]
