In [21]:
import numpy as np

In [22]:

arr1=np.array([1,2,3,4,5])
print("1D array:",arr1)

arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr2)

arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array:",arr3)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]
3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
zeroes_arr=np.zeros((2,3))
print("Zeroes array:",zeroes_arr)

ones_arr=np.ones((3,2))
print("Ones array:",ones_arr)

full_arr=np.full((2,2),7)
print("Full array:",full_arr)

identity_arr=np.eye(4)
print("Identity matrix:",identity_arr)

Zeroes array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full array: [[7 7]
 [7 7]]
Identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
range_arr=np.arange(0,10,3)
print("Array with a range:",range_arr)

line_arr=np.linspace(0,10,5)
print("Linespaced array:",line_arr)

rand_arr=np.random.rand(2,3)
randint_arr=np.random.randint(1,100,size=(2,3))
print("Random array:",rand_arr)
print("RandInt array:",randint_arr)


Array with a range: [0 3 6 9]
Linespaced array: [ 0.   2.5  5.   7.5 10. ]
Random array: [[0.16048904 0.36439518 0.86589814]
 [0.55277871 0.91883799 0.83472065]]
RandInt array: [[12 83 60]
 [56 21 77]]


In [25]:
arr_func=np.array([[1,2,3],[4,5,6]])
print("Shape of array:",arr_func.shape)
print("Dimension of array:",arr_func.ndim)
print("Size of array:",arr_func.size)
print("Datatype of array:",arr_func.dtype)

Shape of array: (2, 3)
Dimension of array: 2
Size of array: 6
Datatype of array: int64


In [26]:
reshaped=arr_func.reshape(3,2)
print("Reshaped array (3x2):",reshaped)

flat=arr_func.flatten()
print("Flatten array",flat)

print("Transpose of array:",arr_func.T)

Reshaped array (3x2): [[1 2]
 [3 4]
 [5 6]]
Flatten array [1 2 3 4 5 6]
Transpose of array: [[1 4]
 [2 5]
 [3 6]]


In [27]:
a=np.array([1,2,3])
b=np.array([4,5,6])
joint=np.concatenate((a,b))
print("Concatenated array:",joint)

stacked_v=np.vstack((a,b))
stacked_h=np.hstack((a,b))
print("Vertical stack:",stacked_v)
print("Horizontal stack",stacked_h)

Concatenated array: [1 2 3 4 5 6]
Vertical stack: [[1 2 3]
 [4 5 6]]
Horizontal stack [1 2 3 4 5 6]


In [28]:
unsorted_arr=([3,5,1,2,7,4])
sorted_arr=np.sort(unsorted_arr)
print("Original:",unsorted_arr)
print("Sorted:",sorted_arr)

Original: [3, 5, 1, 2, 7, 4]
Sorted: [1 2 3 4 5 7]


In [29]:
ex2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", ex2.shape)
print("Size:", ex2.size)
print("Reshaped:\n", ex2.reshape(3, 2))

Shape: (2, 3)
Size: 6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


Mathematical Operations

In [30]:
x=np.array([10,20,30,40,50])
y=np.array([1,2,3,4,5])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)
print("Power:", x ** 2)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Power: [ 100  400  900 1600 2500]


In [31]:
data=np.array([4,5,23,16,20,32,45])

print("Sum:",np.sum(data))
print("Minimum element:",np.min(data))
print("Maximum element",np.max(data))
print("Mean:",np.mean(data))
print("Standard deviation:",np.std(data))
print("Variance:",np.var(data))

Sum: 145
Minimum element: 4
Maximum element 45
Mean: 20.714285714285715
Standard deviation: 13.477115902938007
Variance: 181.63265306122452


In [32]:
nums=np.array([1,4,9,18])
print("Square root:",np.sqrt(nums))
print("Exponent:",np.exp(nums))
print("Natural log:",np.log(nums))
print("Sine:",np.sin(nums))

Square root: [1.         2.         3.         4.24264069]
Exponent: [2.71828183e+00 5.45981500e+01 8.10308393e+03 6.56599691e+07]
Natural log: [0.         1.38629436 2.19722458 2.89037176]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.75098725]


In [33]:
m1=np.array([[1,2],[4,5]])
m2=np.array([[5,6],[7,8]])

print("Element wise multiplication:\n",m1*m2)
print("Matrix multiplication(dot)",np.dot(m1,m2))
print("Matrix multiplication(matmul)",np.matmul(m1,m2))

Element wise multiplication:
 [[ 5 12]
 [28 40]]
Matrix multiplication(dot) [[19 22]
 [55 64]]
Matrix multiplication(matmul) [[19 22]
 [55 64]]


In [34]:
p=np.array([1,2,3,4,5])
q=np.array([4,5,6,7,8])
ex3_sum=p+q
ex3_product=p*q
print("Sum:",ex3_sum)
print("Product:",ex3_product)
print("Mean of sum:",np.mean(ex3_sum))

Sum: [ 5  7  9 11 13]
Product: [ 4 10 18 28 40]
Mean of sum: 9.0


In [35]:
arr=np.array([10,20,30,40,50,60])
print("Full array:",arr)
print("first element:",arr[0])
print("Last element",arr[-1])
print("Elements from index 1 to 4",arr[1:5])
print("Elements from index 0 to 5 with the gap of 3",arr[0:6:3])
print("Every second element:",arr[::2])
print("Reversed array:",arr[::-1])

Full array: [10 20 30 40 50 60]
first element: 10
Last element 60
Elements from index 1 to 4 [20 30 40 50]
Elements from index 0 to 5 with the gap of 3 [10 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [36]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print("Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
